### ISSUE TITLE
Build is not working

### ISSUE THREAD

**Issue by RosilBelli** [jlooper/mixology-mobile#1]
Hi!

I tried to build with tns run android --bundle but got the error:

`
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
   Searched Location:
  D:\PROJETOS\_TMP\mixology-mobile-master\platforms\android\app\src\nullnull\debug\google-services.json
  D:\PROJETOS\_TMP\mixology-mobile-master\platforms\android\app\src\debug\nullnull\google-services.json
  D:\PROJETOS\_TMP\mixology-mobile-master\platforms\android\app\src\nullnull\google-services.json
  D:\PROJETOS\_TMP\mixology-mobile-master\platforms\android\app\src\debug\google-services.json
  D:\PROJETOS\_TMP\mixology-mobile-master\platforms\android\app\src\nullnullDebug\google-services.json
  D:\PROJETOS\_TMP\mixology-mobile-master\platforms\android\app\google-services.json

Unable to copy google-services.json.
`

Trying to build on a Windows computer.

**Comment by jlooper** [comment]
Yes, there's a file missing there. I haven't implemented this for Android yet. You can hook it up to your own Firebase account though and go from there.
